### PR TITLE
new platform icons

### PR DESCRIPTION
**Pull request by shujuuu**
Make all strokes thicker and more consistent. See some examples below.

Screen Shot 2022-12-22 at 8 59 43 PM

Screen Shot 2022-12-22 at 8 56 45 PM

### CODE REVIEW

**Comment by YossiSaadi** [comment]
# 👑

**Review by talkor — DISMISSED** [review]
@shujuuu you're the best!!
The new icons look really good. Also just FYI, since we generate a an icon font out of these, they will all be generated in a single color and get the color from CSS, some icons like the shield icon are "painted" with a gradient using CSS since we get it all black.

**Comment by shujuuu** [comment]
Thanks @talkor @YossiSaadi! How do I know if the icons look good on our swimm app? Will I automatically see it on staging after merge?

**Comment by talkor** [comment]
> Thanks @talkor @YossiSaadi! How do I know if the icons look good on our swimm app? Will I automatically see it on staging after merge?

No, there's another step after merging this PR. I added a commit to this PR that changes the version number to 2.0.0 (in the `package.json` file), we need to generate a new tag (a.k.a release/version) for this PR after it's merged. Only after that, we can go back to the `swimm` repo, and installed the new tag (2.0.0) and see the new icons. There are some [instructions here](https://github.com/swimmio/fontaweswimm/blob/main/.swm/adding-icons-to-fontaweswimm.gX4HLtSjzpbsKwyUS7oa.sw.md#steps-to-add-a-new-icon)

**Comment by talkor** [comment]
@shujuuu I'll take it from here, I'd be happy to show you how I did the rest when you come back from vacation :) Happy holidays 🥳

**Pull request merged**
